services:
  wordpress:
    image: wordpress:php8.2-fpm
    container_name: ${PROJECT_NAME}
    ports:
      - "8080"
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}:${DB_PORT}
      WORDPRESS_DB_USER: ${DB_USERNAME}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_DATABASE}
      WORDPRESS_AUTH_KEY: ${AUTH_KEY}
      WORDPRESS_SECURE_AUTH_KEY: ${SECURE_AUTH_KEY}
      WORDPRESS_LOGGED_IN_KEY: ${LOGGED_IN_KEY}
      WORDPRESS_NONCE_KEY: ${NONCE_KEY}
      WORDPRESS_AUTH_SALT: ${AUTH_SALT}
      WORDPRESS_SECURE_AUTH_SALT: ${SECURE_AUTH_SALT}
      WORDPRESS_LOGGED_IN_SALT: ${LOGGED_IN_SALT}
      WORDPRESS_NONCE_SALT: ${NONCE_SALT}
      WORDPRESS_TABLE_PREFIX: ${TABLE_PREFIX}
      WORDPRESS_DEBUG: ${DEBUG}
      WORDPRESS_CONFIG_EXTRA: ${CONFIG_EXTRA}
    volumes:
      - ./${PROJECT_NAME}:/var/www/html

  nginx:
    image: nginx:alpine
    container_name: ${PROJECT_NAME}_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./${PROJECT_NAME}:/var/www/html
    depends_on:
      - wordpress

volumes:
  db_data:
